### ISSUE TITLE
Android Trace Issue

### ISSUE THREAD

**Issue by tr33s** [0xdea/frida-scripts#1]
Hello, I am using raptor_frida_android_trace.js and I am getting an error upon the app being spawned.

`Spawned APP. Resuming main thread!
[DEVICE::APP]-> TypeError: cannot read property 1 of null
    at [anon] (duk_hobject_props.c:2385)
    at [anon] (repl1.js:46)
    at frida/node_modules/frida-java/index.js:190
    at forEach (native)
    at d (java.js:2216)
    at frida/node_modules/frida-java/index.js:120
    at trace (repl1.js:51)
    at [anon] (repl1.js:174)
    at frida/node_modules/frida-java/lib/vm.js:39
    at v (frida/node_modules/frida-java/index.js:338)
    at frida/node_modules/frida-java/index.js:309
    [...]`

It looks like the issue is on line 46:
`var className = aClass.match(/[L](.*);/)[1].replace(/\//g, ".");`

Is there an easy fix like a null check? Could this issue be caused by obfuscation?

**Comment by 0xdea** [comment]
Hi,

First of all please make sure that you're following the directions outlined at: 

https://techblog.mediaservice.net/2017/09/tracing-arbitrary-methods-and-function-calls-on-android-and-ios/

The issue you're experiencing might also be caused by the fact that Frida is updated very often and something might have become broken in my scripts... Or by something specific related to your device/app. If possible, you should:

- try tracing another app
- try tracing the same app on another device
- try tracing using an older/newer Frida version

You should also consider using Brida:

https://github.com/federicodotta/Brida
https://techblog.mediaservice.net/2018/04/brida-a-step-by-step-user-guide/

It's well tested and maintained and, among other things, it's basically a GUI for my scripts.

Finally, for Frida-related questions you should join the official Telegram channel:

https://telegram.me/fridadotre

I hope this helps!

**Comment by sk3ptre** [comment]
I get the same error, just wanted to check if there was any easy fix for this ?
@tr33s - Were you able to resolve this or find a workaround ?

**Comment by tr33s** [comment]
@sk3ptre I was not able to find a fix. I do believe it was because of obfuscation.

**Comment by h3rb0** [comment]
I guess the code 
`var className = aClass.match(/[L](.*);/)[1].replace(/\//g, "."); `
 is just used for extract the class name from aClass "Lcom.example.app;". but in my case, the value of aClass is "com.example.app". 
Therefor , just  
`var className = aClase;
`

**Comment by leoandrade20** [comment]
Hello, I'm trying to display a Toast message through Frida with this code: 

```
Java.perform(() => {
     var context = Java.use("android.app.ActivityThread").currentApplication().getApplicationContext();
     
     Java.scheduleOnMainThread(function() {
          var toast = Java.use("android.widget.Toast");
          toast.makeText(context, Java.use("java.lang.String").$new("Hellooo !!"), 1).show();
    });
});
```
However, I still get the error:
`TypeError: cannot read property 'getApplicationContext' of null`
